### ISSUE TITLE
A problem when running the train.py

### ISSUE THREAD

**Issue by kagawa588** [xing0047/TPS#10]
Hi, 

Thanks for your great work! 

I met a problem when I run the train.py ,

CUDA_VISIBLE_DEVICES=0 python train.py --cfg configs/tps_syn2city.yml 
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from tps.model.accel_deeplabv2 import get_accel_deeplab_v2
ModuleNotFoundError: No module named 'tps'

Could you pls give any suggestions?

And The link for downloading optical flow is not accessible, could you pls update them?

Thank you

**Comment by xing0047** [comment]
Hi,

Thanks for your interest in our work!

For your question, I suggest to add 'tps' to the system path so that computer will find where the module is while running.

Best,
Yun
