### ISSUE TITLE
Question about the preprocess of the Synthia dataset

### ISSUE THREAD

**Issue by mai556** [xing0047/TPS#13]
https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/dataset/SynthiaSeq.py#L22
Hi! I wonder why the Synthia dataset is cropped from (760, 1280) to (640, 1280). I feel a little confused. 

Thanks

**Comment by xing0047** [comment]
Hi,

We strictly follow dataset setting in baseline method DA-VSN to ensure a fair comparison. Please find it in DA-VSN repo.

Best,
Yun
