### ISSUE TITLE
Question about the dataset SEQS-04-DAWN

### ISSUE THREAD

**Issue by ZHE-SAPI** [xing0047/TPS#3]
A very nice job! But I also encountered the same problem, and the SEQS-04-DAWN folder I downloaded has two subfolders, RGB and GT, and the RGB folder has two angles, Stereo_Right and Stereo_Left,

And the folders of both angles contain four folders: Omni_B, Omni_F, Omni_L, and Omni_R. What kind of files are used in the document?

In addition, each file only contains 850 pictures, which does not seem to correspond to the 8000 frames mentioned in the article. I would like to ask for your advice, thank you very much! !

**Comment by xing0047** [comment]
Hi, 

Thanks for your interest in our work. For your issue, please refer to https://github.com/Dayan-Guan/DA-VSN/issues/3#issuecomment-919267300. We follow the same setting as in DA-VSN.

Best,
Yun

**Comment by ZHE-SAPI** [comment]
Hi,
Thank you for your quick reply.

Best,
Zhe
